---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ruby-env::default]
    attributes: {"ruby": {"version": "2.2.1"}}
---