name 'ruby-env'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ruby-env'
long_description 'Installs/Configures ruby-env'
version '0.1.0'
depends 'rbenv', '~> 1.7.1'
