name 'ruby-study-env'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hirayama-env'
long_description 'Installs/Configures hirayama-env'
version '0.1.0'
depends 'docker', '~> 2.0'
depends 'chef-dk', '~> 3.0.0'
depends 'python', '~> 1.4.6'
depends 'awscli', '~> 1.1.2'
depends 'aws', '~> 2.7.2'
depends 'java', '~> 1.36.0'
depends 'chrome', '~> 1.1.1'